In [1]:
from google.colab import files

uploaded = files.upload()

Saving 항만시설 및 하역능력정보_2024.csv to 항만시설 및 하역능력정보_2024.csv
Saving 항만시설 및 하역능력정보_2021.csv to 항만시설 및 하역능력정보_2021.csv
Saving 항만시설 및 하역능력정보_2022.csv to 항만시설 및 하역능력정보_2022.csv

In [2]:
from google.colab import drive
drive.mount('/content/drive')

import os

base_path = "/content/drive/MyDrive/contest_changwon_port"

folders = [
    "data/raw/port_calls",
    "data/raw/port_facility",
    "data/raw/ship_spec",
    "data/raw/trucking_company",
    "data/raw/freight_forwarder",
    "data/processed",
    "output/tables",
    "output/figures"
]

for folder in folders:
    path = os.path.join(base_path, folder)
    os.makedirs(path, exist_ok=True)
    print("생성/확인 완료:", path)

Mounted at /content/drive
생성/확인 완료: /content/drive/MyDrive/contest_changwon_port/data/raw/port_calls
생성/확인 완료: /content/drive/MyDrive/contest_changwon_port/data/raw/port_facility
생성/확인 완료: /content/drive/MyDrive/contest_changwon_port/data/raw/ship_spec
생성/확인 완료: /content/drive/MyDrive/contest_changwon_port/data/raw/trucking_company
생성/확인 완료: /content/drive/MyDrive/contest_changwon_port/data/raw/freight_forwarder
생성/확인 완료: /content/drive/MyDrive/contest_changwon_port/data/processed
생성/확인 완료: /content/drive/MyDrive/contest_changwon_port/output/tables
생성/확인 완료: /content/drive/MyDrive/contest_changwon_port/output/figures

In [7]:
import os

base_path = "/content/drive/MyDrive/contest_changwon_port"

port_facility_path = os.path.join(base_path, "data/raw/port_facility")
os.makedirs(port_facility_path, exist_ok=True)

print("폴더 생성/확인 완료:", port_facility_path)

폴더 생성/확인 완료: /content/drive/MyDrive/contest_changwon_port/data/raw/port_facility

In [8]:
import glob
import os

files = glob.glob(os.path.join(port_facility_path, "*.csv"))

print("파일 수:", len(files))

for f in files:
    print(os.path.basename(f))

파일 수: 3
항만시설 및 하역능력정보_2021.csv
항만시설 및 하역능력정보_2022.csv
항만시설 및 하역능력정보_2024.csv

In [11]:
import glob
import os

port_facility_path = os.path.join(base_path, "data/raw/port_facility")

files = glob.glob(os.path.join(port_facility_path, "*.csv"))

print("전체 파일 수:", len(files))

for f in files:
    print(os.path.basename(f))

전체 파일 수: 3
항만시설 및 하역능력정보_2021.csv
항만시설 및 하역능력정보_2022.csv
항만시설 및 하역능력정보_2024.csv

21, 22, 24 파일만 선택

In [12]:
target_years = ["2021", "2022", "2024"]

selected_files = [
    f for f in files
    if any(year in os.path.basename(f) for year in target_years)
]

print("선택된 파일 수:", len(selected_files))

for f in selected_files:
    print(os.path.basename(f))

선택된 파일 수: 3
항만시설 및 하역능력정보_2021.csv
항만시설 및 하역능력정보_2022.csv
항만시설 및 하역능력정보_2024.csv

파일 불러오고 통합

In [13]:
import pandas as pd
import re

df_list = []

for file in selected_files:
    df = pd.read_csv(file, encoding="utf-8-sig")

    year_match = re.search(r"20\d{2}", os.path.basename(file))
    if year_match:
        df["year"] = int(year_match.group())

    df["source_file"] = os.path.basename(file)
    df_list.append(df)

port_facility = pd.concat(df_list, ignore_index=True)

print("통합 데이터 크기:", port_facility.shape)
display(port_facility.head())
print(port_facility.columns)

통합 데이터 크기: (9265, 14)

,prtAgCd,prtAgNm,fcltyCd,fcltySubCd,fcltyKorNm,fcltyEngNm,fcltyAppnTy,useFeeKorNm,lnlDvicNm,lnlAblty,trtmntFrghtNm,berthNm,year,source_file
0,20,부산,*AG,01,욕망산 사석 적출장,NaN,1.0,정박료,NaN,NaN,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv
1,20,부산,*AG,02,안골.와성지구 매립,NaN,1.0,정박료,NaN,NaN,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv
2,20,부산,*BH,01,남측 컨테이너 배후단지,NaN,1.0,정박료,NaN,NaN,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv
3,20,부산,*DL,01,선진조선,NaN,2.0,면제,NaN,0.0,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv
4,20,부산,*DP,01,선진2조선,NaN,2.0,면제,NaN,0.0,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv

Index(['prtAgCd', 'prtAgNm', 'fcltyCd', 'fcltySubCd', 'fcltyKorNm',
       'fcltyEngNm', 'fcltyAppnTy', 'useFeeKorNm', 'lnlDvicNm', 'lnlAblty',
       'trtmntFrghtNm', 'berthNm', 'year', 'source_file'],
      dtype='object')

In [14]:
print(port_facility["year"].value_counts().sort_index())  # 연도 확

year
2021    3026
2022    3112
2024    3127
Name: count, dtype: int64

In [15]:
print(port_facility["prtAgNm"].unique()) # 항만명 확인

['부산' '인천' '평택' '인천연안' '용기포' '연평도' '서울' '경인' nan '동해' '삼척' '묵호' '속초' '옥계'
 '호산' '대산' '보령' '태안' '당진화력' '군산' '장항' '고정' '상왕등도' '흑산도' '목포' '완도' '대불분실'
 '북항분실' '여수' '여천' '광양' '하동' '월내' '중흥' '거문도' '포항' '포항신항' '영일만항' '후포' '울릉도동'
 '울릉사동' '마산' '삼천포' '옥포' '장승포' '진해' '통영' '고현' '울산' '온산' '미포' '제주' '서귀포']

마산항, 진해항만 필터링

In [16]:
target_ports = ["마산", "진해"]

port_facility_changwon = port_facility[
    port_facility["prtAgNm"].astype(str).str.contains("|".join(target_ports), na=False)
].copy()

print("마산·진해 항만시설 데이터 크기:", port_facility_changwon.shape)

print("항만명:")
print(port_facility_changwon["prtAgNm"].unique())

print("연도별 데이터 수:")
print(port_facility_changwon["year"].value_counts().sort_index())

display(port_facility_changwon.head())

마산·진해 항만시설 데이터 크기: (419, 14)
항만명:
['마산' '진해']
연도별 데이터 수:
year
2021    131
2022    144
2024    144
Name: count, dtype: int64

,prtAgCd,prtAgNm,fcltyCd,fcltySubCd,fcltyKorNm,fcltyEngNm,fcltyAppnTy,useFeeKorNm,lnlDvicNm,lnlAblty,trtmntFrghtNm,berthNm,year,source_file
2366,810,마산,MB1,01,1부두 11선석,NaN,1.0,접안료,NaN,NaN,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv
2367,810,마산,MB1,02,1부두 12선석,NaN,4.0,접안료,NaN,NaN,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv
2368,810,마산,MB1,03,1부두 13선석,NaN,4.0,접안료,NaN,NaN,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv
2369,810,마산,MB1,04,1부두 14선석,NaN,4.0,접안료,NaN,NaN,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv
2370,810,마산,MB1,J1,진해1부두 11선석,NaN,4.0,NaN,NaN,NaN,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv

하역능력 컬럼 숫자형 정리

In [17]:
port_facility_changwon["lnlAblty"] = (
    port_facility_changwon["lnlAblty"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("-", "0", regex=False)
    .str.strip()
)

port_facility_changwon["lnlAblty"] = pd.to_numeric(
    port_facility_changwon["lnlAblty"],
    errors="coerce"
).fillna(0)

In [18]:
lnl_check = (
    port_facility_changwon
    .groupby(["year", "prtAgNm"], as_index=False)
    .agg(
        facility_count=("fcltyKorNm", "count"),
        lnlAblty_sum=("lnlAblty", "sum"),
        lnlAblty_nonzero=("lnlAblty", lambda x: (x > 0).sum())
    )
)

display(lnl_check)

   year prtAgNm  facility_count  lnlAblty_sum  lnlAblty_nonzero
0  2021      마산             108           0.0                 0
1  2021      진해              23           0.0                 0
2  2022      마산             108           0.0                 0
3  2022      진해              36           0.0                 0
4  2024      마산             108           0.0                 0
5  2024      진해              36           0.0                 0

lnlAblty_nonzero가 거의 0이면, 이 데이터에서는 하역능력 수치 분석보다 시설 수·시설명 중심 분석으로 가야

In [19]:
# 연도별 항만별 시설 수 집계

facility_yearly = (
    port_facility_changwon
    .groupby(["year", "prtAgNm"], as_index=False)
    .agg(
        facility_count=("fcltyKorNm", "count"),
        unique_facility_code=("fcltyCd", "nunique"),
        unique_facility_name=("fcltyKorNm", "nunique"),
        total_lnlAblty=("lnlAblty", "sum")
    )
)

display(facility_yearly)

,year,prtAgNm,facility_count,unique_facility_code,unique_facility_name,total_lnlAblty
0,2021,마산,108,38,107,0.0
1,2021,진해,23,8,22,0.0
2,2022,마산,108,38,107,0.0
3,2022,진해,36,8,31,0.0
4,2024,마산,108,38,107,0.0
5,2024,진해,36,8,22,0.0

2021, 2022, 2024년에 마산항과 진해항의 항만시설 항목 수가 얼마나 되는지 확인할 수 있음

In [20]:
# 시설 구분별 집계

facility_type_summary = (
    port_facility_changwon
    .groupby(["year", "prtAgNm", "useFeeKorNm"], as_index=False)
    .size()
    .rename(columns={"size": "count"})
)

display(facility_type_summary)

    year prtAgNm useFeeKorNm  count
0   2021      마산          면제      5
1   2021      마산         접안료     71
2   2021      마산         정박료     22
3   2021      진해          접안      1
4   2021      진해         접안료     19
5   2021      진해         정박료      3
6   2022      마산          면제      5
7   2022      마산         접안료     71
8   2022      마산         정박료     22
9   2022      진해          접안      1
10  2022      진해         접안료     30
11  2022      진해          정박      1
12  2022      진해         정박료      4
13  2024      마산          면제      5
14  2024      마산         접안료     71
15  2024      마산         정박료     22
16  2024      진해          접안      1
17  2024      진해         접안료     30
18  2024      진해          정박      1
19  2024      진해         정박료      4

useFeeKorNm은 접안료, 정박료 같은 시설/사용료 구분 - 마산항·진해항 시설이 접안, 정박, 하역 등 어떤 기능과 관련되어 있는지 확인할 수 있음

In [21]:
# 마산항 시설명

masan_facility_names = (
    port_facility_changwon[port_facility_changwon["prtAgNm"] == "마산"]
    [["year", "fcltyKorNm", "useFeeKorNm", "lnlDvicNm", "lnlAblty", "trtmntFrghtNm", "berthNm"]]
    .drop_duplicates()
)

display(masan_facility_names.head(50))

,year,fcltyKorNm,useFeeKorNm,lnlDvicNm,lnlAblty,trtmntFrghtNm,berthNm
2366,2021,1부두 11선석,접안료,NaN,0.0,NaN,NaN
2367,2021,1부두 12선석,접안료,NaN,0.0,NaN,NaN
2368,2021,1부두 13선석,접안료,NaN,0.0,NaN,NaN
2369,2021,1부두 14선석,접안료,NaN,0.0,NaN,NaN
2370,2021,진해1부두 11선석,NaN,NaN,0.0,NaN,NaN
2371,2021,진해1부두 12선석,NaN,NaN,0.0,NaN,NaN
2372,2021,진해1부두 13선석,NaN,NaN,0.0,NaN,NaN
2373,2021,진해1부두 14선석,NaN,NaN,0.0,NaN,NaN
2374,2021,진해1부두 15선석,NaN,NaN,0.0,NaN,NaN
2375,2021,진해 1부두 16선석,접안료,NaN,0.0,NaN,NaN
2376,2021,2부두 21선석,접안료,NaN,0.0,NaN,NaN
2377,2021,2부두 22선석,접안료,NaN,0.0,NaN,NaN
2378,2021,2부두 23선석,접안료,NaN,0.0,NaN,NaN
2379,2021,진해2부두 21선석,NaN,NaN,0.0,NaN,NaN
2380,2021,진해2부두 22선석,NaN,NaN,0.0,NaN,NaN
2381,2021,진해2부두 23선석,NaN,NaN,0.0,NaN,NaN
2382,2021,3부두 31선석,접안료,NaN,0.0,NaN,NaN
2383,2021,3부두 32선석,접안료,NaN,0.0,NaN,NaN
2384,2021,3부두 33선석,접안료,NaN,0.0,NaN,NaN
2385,2021,3부두 34선석,접안료,NaN,0.0,NaN,NaN
2386,2021,4부두 41선석,접안료,NaN,0.0,NaN,NaN
2387,2021,4부두 42선석,접안료,NaN,0.0,NaN,NaN
2388,2021,4부두 43선석,접안료,NaN,0.0,NaN,NaN
2389,2021,4부두 44선석,접안료,NaN,0.0,NaN,NaN
2390,2021,4부두 45선석,접안료,NaN,0.0,NaN,NaN
2391,2021,4부두 46선석,접안료,NaN,0.0,NaN,NaN
2392,2021,4부두 47선석,접안료,NaN,0.0,NaN,NaN
2393,2021,4부두 48선석,접안료,NaN,0.0,NaN,NaN
2394,2021,4부두 49선석,접안료,NaN,0.0,NaN,NaN
2395,2021,4부두 49-1선석,접안료,NaN,0.0,NaN,NaN
2396,2021,제5부두 51선석(공용),접안료,NaN,0.0,NaN,NaN
2397,2021,제5부두 52선석(공용),접안료,NaN,0.0,NaN,NaN
2398,2021,제5부두 53선석(공용),접안료,NaN,0.0,NaN,NaN
2399,2021,제5부두 54선석(공용),접안료,NaN,0.0,NaN,NaN
2400,2021,제5부두 55선석(TOC),접안료,NaN,0.0,NaN,NaN
2401,2021,제5부두 56선석(TOC),접안료,NaN,0.0,NaN,NaN
2402,2021,제5부두 57선석(TOC),접안료,NaN,0.0,NaN,NaN
2403,2021,제5부두 58선석(TOC),접안료,NaN,0.0,NaN,NaN
2404,2021,두산중공업부두,접안료,NaN,0.0,NaN,NaN
2405,2021,중앙부두 1선석,접안료,NaN,0.0,NaN,NaN
2406,2021,수협부두 1선석,접안료,NaN,0.0,NaN,NaN
2407,2021,코드오류자료,NaN,NaN,0.0,NaN,NaN
2408,2021,동양부두,접안료,NaN,0.0,NaN,NaN
2409,2021,동림부두,정박료,NaN,0.0,NaN,NaN
2410,2021,한국철강부두,접안료,NaN,0.0,NaN,NaN
2411,2021,적현부두,정박료,NaN,0.0,NaN,NaN
2412,2021,두산엔진부두,접안료,NaN,0.0,NaN,NaN
2413,2021,가포신항부두 1선석,면제,NaN,0.0,NaN,NaN
2414,2021,가포신항부두 2선석,면제,NaN,0.0,NaN,NaN
2415,2021,가포신항부두 3선석,면제,NaN,0.0,NaN,NaN

In [22]:
# 진해항 시설명


jinhae_facility_names = (
    port_facility_changwon[port_facility_changwon["prtAgNm"] == "진해"]
    [["year", "fcltyKorNm", "useFeeKorNm", "lnlDvicNm", "lnlAblty", "trtmntFrghtNm", "berthNm"]]
    .drop_duplicates()
)

display(jinhae_facility_names.head(50))

      year  fcltyKorNm useFeeKorNm lnlDvicNm  lnlAblty trtmntFrghtNm berthNm
2541  2021   1부두 11 선석         접안료       NaN       0.0           NaN     NaN
2542  2021   1부두 12 선석         접안료       NaN       0.0           NaN     NaN
2543  2021    1부두 13선석         접안료       NaN       0.0           NaN     NaN
2544  2021    1부두 14선석         접안료       NaN       0.0           NaN     NaN
2545  2021    1부두 15선석         접안료       NaN       0.0           NaN     NaN
2546  2021   1부두 16 선석         접안료       NaN       0.0           NaN     NaN
2547  2021   2부두 21 선석         접안료       NaN       0.0           NaN     NaN
2548  2021  2 부두 22 선석         접안료       NaN       0.0           NaN     NaN
2549  2021  2 부두 23 선석         접안료       NaN       0.0           NaN     NaN
2550  2021    2부두 24선석          접안       NaN       0.0           NaN     NaN
2551  2021    2부두 25선석         접안료       NaN       0.0           NaN     NaN
2552  2021    진해부두 물량장         접안료       NaN       0.0           NaN     NaN
2554  2021       군용물량장         접안료       NaN       0.0           NaN     NaN
2555  2021  1 부두 1 야적장         접안료       NaN       0.0           NaN     NaN
2556  2021  1 부두 2 야적장         접안료       NaN       0.0           NaN     NaN
2557  2021  1 부두 3 야적장         접안료       NaN       0.0           NaN     NaN
2558  2021  2 부두 1 야적장         접안료       NaN       0.0           NaN     NaN
2559  2021  2 부두 2 야적장         접안료       NaN       0.0           NaN     NaN
2560  2021  2 부두 3 야적장         접안료       NaN       0.0           NaN     NaN
2561  2021      A 1 박지         정박료       NaN       0.0           NaN     NaN
2562  2021      A 2 박지         정박료       NaN       0.0           NaN     NaN
2563  2021      검역박지 Q         정박료       NaN       0.0           NaN     NaN
5638  2022  1 부두 11 선석         접안료       NaN       0.0           NaN     NaN
5639  2022  1 부두 12 선석          접안       NaN       0.0           NaN     NaN
5640  2022  1 부두 13 선석         접안료       NaN       0.0           NaN     NaN
5641  2022  1 부두 14 선석         접안료       NaN       0.0           NaN     NaN
5642  2022  1 부두 15 선석         접안료       NaN       0.0           NaN     NaN
5643  2022  1 부두 16 선석         접안료       NaN       0.0           NaN     NaN
5644  2022   1부두 11 선석         접안료       NaN       0.0           NaN     NaN
5645  2022   1부두 12 선석         접안료       NaN       0.0           NaN     NaN
5646  2022    1부두 13선석         접안료       NaN       0.0           NaN     NaN
5647  2022    1부두 14선석         접안료       NaN       0.0           NaN     NaN
5648  2022    1부두 15선석         접안료       NaN       0.0           NaN     NaN
5649  2022   1부두 16 선석         접안료       NaN       0.0           NaN     NaN
5650  2022  2 부두 21 선석         접안료       NaN       0.0           NaN     NaN
5651  2022  2 부두 22 선석         접안료       NaN       0.0           NaN     NaN
5652  2022  2 부두 23 선석         접안료       NaN       0.0           NaN     NaN
5653  2022  2 부두 24 선석         접안료       NaN       0.0           NaN     NaN
5654  2022  2 부두 25 선석         접안료       NaN       0.0           NaN     NaN
5655  2022   2부두 21 선석         접안료       NaN       0.0           NaN     NaN
5658  2022    2부두 24선석         접안료       NaN       0.0           NaN     NaN
5659  2022    2부두 25선석         접안료       NaN       0.0           NaN     NaN
5660  2022    진해부두 물량장         접안료       NaN       0.0           NaN     NaN
5662  2022       군용물량장         접안료       NaN       0.0           NaN     NaN
5663  2022  1 부두 1 야적장         접안료       NaN       0.0           NaN     NaN
5664  2022  1 부두 2 야적장         접안료       NaN       0.0           NaN     NaN
5665  2022  1 부두 3 야적장         접안료       NaN       0.0           NaN     NaN
5666  2022  2 부두 1 야적장         접안료       NaN       0.0           NaN     NaN
5667  2022  2 부두 2 야적장         접안료       NaN       0.0           NaN     NaN
5668  2022  2 부두 3 야적장         접안료       NaN       0.0           NaN     NaN

이 표는 보고서에서 *대표 시설 예시*로 쓰면 좋을듯

In [23]:
# 취급화물명 확인

cargo_summary = (
    port_facility_changwon
    .dropna(subset=["trtmntFrghtNm"])
    .groupby(["year", "prtAgNm", "trtmntFrghtNm"], as_index=False)
    .size()
    .rename(columns={"size": "count"})
)

display(cargo_summary.head(50))

Empty DataFrame
Columns: [year, prtAgNm, trtmntFrghtNm, count]
Index: []

취급화물명 확인 결과는 No entries - port_facility_changwon 안에서 trtmntFrghtNm, 즉 취급화물명 컬럼이 마산·진해 데이터에서는 비어 있음
-> 마산항은 컨테이너 화물을 주로 취급 / 진해항은 벌크화물을 주로 취급

In [24]:
# 선석명 확인

berth_summary = (
    port_facility_changwon
    .dropna(subset=["berthNm"])
    .groupby(["year", "prtAgNm", "berthNm"], as_index=False)
    .size()
    .rename(columns={"size": "count"})
)

display(berth_summary.head(50))

Empty DataFrame
Columns: [year, prtAgNm, berthNm, count]
Index: []

count가 실제 선석 개수를 의미하는 건 아님
같은 선석이 여러 시설 항목에 반복해서 나올 수 있어서 count는 등록 횟수에 가까움
마산항과 진해항에 어떤 선석 또는 접안시설 명칭이 등록되어 있는지 확인하는 보조자료로 활용

취급화물명: 값이 없어 분석 제외
선석명: 항만시설 위치·접안시설 명칭 확인용으로 활용
하역능력: 0 또는 결측이 많으면 총량 비교는 제한
핵심 분석: 시설 수, 시설명, 사용료 구분, 선석명 중심

이 데이터의 최종 역할은: 마산항과 진해항의 항만시설 기반이 존재한다는 것을 확인하는 자료

In [25]:
processed_path = os.path.join(base_path, "data/processed")
os.makedirs(processed_path, exist_ok=True)

facility_yearly.to_csv(
    os.path.join(processed_path, "changwon_port_facility_yearly_2021_2022_2024.csv"),
    index=False,
    encoding="utf-8-sig"
)

facility_type_summary.to_csv(
    os.path.join(processed_path, "changwon_port_facility_type_summary_2021_2022_2024.csv"),
    index=False,
    encoding="utf-8-sig"
)

cargo_summary.to_csv(
    os.path.join(processed_path, "changwon_port_facility_cargo_summary_2021_2022_2024.csv"),
    index=False,
    encoding="utf-8-sig"
)

berth_summary.to_csv(
    os.path.join(processed_path, "changwon_port_facility_berth_summary_2021_2022_2024.csv"),
    index=False,
    encoding="utf-8-sig"
)

port_facility_changwon.to_csv(
    os.path.join(processed_path, "changwon_port_facility_filtered_2021_2022_2024.csv"),
    index=False,
    encoding="utf-8-sig"
)

print("항만시설 및 하역능력정보 2021, 2022, 2024 분석 결과 저장 완료")

항만시설 및 하역능력정보 2021, 2022, 2024 분석 결과 저장 완료

이 분석은 마산항·진해항의 항만시설 기반이 실제로 존재하는지 확인하기 위한 단계이고, 결론은 “창원 항만권역에는 항만시설 기반이 확인되지만, 하역능력·취급화물 정보가 부족해 시설 현황 중심으로만 활용해야 한다

여기부터는 부산만 뽑아서 한 거

In [26]:
print(port_facility["prtAgNm"].unique())

['부산' '인천' '평택' '인천연안' '용기포' '연평도' '서울' '경인' nan '동해' '삼척' '묵호' '속초' '옥계'
 '호산' '대산' '보령' '태안' '당진화력' '군산' '장항' '고정' '상왕등도' '흑산도' '목포' '완도' '대불분실'
 '북항분실' '여수' '여천' '광양' '하동' '월내' '중흥' '거문도' '포항' '포항신항' '영일만항' '후포' '울릉도동'
 '울릉사동' '마산' '삼천포' '옥포' '장승포' '진해' '통영' '고현' '울산' '온산' '미포' '제주' '서귀포']

In [27]:
# 부산 데이터 추출
port_facility_busan = port_facility[
    port_facility["prtAgNm"].astype(str).str.contains("부산", na=False)
].copy()

print("부산 항만시설 데이터 크기:", port_facility_busan.shape)

print("항만명:")
print(port_facility_busan["prtAgNm"].unique())

print("연도별 데이터 수:")
print(port_facility_busan["year"].value_counts().sort_index())

display(port_facility_busan.head())

부산 항만시설 데이터 크기: (1197, 14)
항만명:
['부산']
연도별 데이터 수:
year
2021    394
2022    398
2024    405
Name: count, dtype: int64

,prtAgCd,prtAgNm,fcltyCd,fcltySubCd,fcltyKorNm,fcltyEngNm,fcltyAppnTy,useFeeKorNm,lnlDvicNm,lnlAblty,trtmntFrghtNm,berthNm,year,source_file
0,20,부산,*AG,01,욕망산 사석 적출장,NaN,1.0,정박료,NaN,NaN,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv
1,20,부산,*AG,02,안골.와성지구 매립,NaN,1.0,정박료,NaN,NaN,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv
2,20,부산,*BH,01,남측 컨테이너 배후단지,NaN,1.0,정박료,NaN,NaN,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv
3,20,부산,*DL,01,선진조선,NaN,2.0,면제,NaN,0.0,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv
4,20,부산,*DP,01,선진2조선,NaN,2.0,면제,NaN,0.0,NaN,NaN,2021,항만시설 및 하역능력정보_2021.csv

In [28]:
# 부산 항만시설 연도별 요약

busan_facility_yearly = (
    port_facility_busan
    .groupby(["year", "prtAgNm"], as_index=False)
    .agg(
        facility_count=("fcltyKorNm", "count"),
        unique_facility_code=("fcltyCd", "nunique"),
        unique_facility_name=("fcltyKorNm", "nunique"),
        total_lnlAblty=("lnlAblty", "sum")
    )
)

display(busan_facility_yearly)

,year,prtAgNm,facility_count,unique_facility_code,unique_facility_name,total_lnlAblty
0,2021,부산,394,165,387,0.0
1,2022,부산,398,166,391,0.0
2,2024,부산,405,168,398,0.0

In [30]:
# 부산 하역능력 값 확인

port_facility_busan["lnlAblty"] = (
    port_facility_busan["lnlAblty"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("-", "0", regex=False)
    .str.strip()
)

port_facility_busan["lnlAblty"] = pd.to_numeric(
    port_facility_busan["lnlAblty"],
    errors="coerce"
).fillna(0)

busan_lnl_check = (
    port_facility_busan
    .groupby(["year", "prtAgNm"], as_index=False)
    .agg(
        facility_count=("fcltyKorNm", "count"),
        lnlAblty_sum=("lnlAblty", "sum"),
        lnlAblty_nonzero=("lnlAblty", lambda x: (x > 0).sum())
    )
)

display(busan_lnl_check)

   year prtAgNm  facility_count  lnlAblty_sum  lnlAblty_nonzero
0  2021      부산             394           0.0                 0
1  2022      부산             398           0.0                 0
2  2024      부산             405           0.0                 0

nlAblty_nonzero가 크면 부산은 하역능력 분석도 어느 정도 가능하고,
0이 많으면 마산·진해처럼 시설 수 중심으로 봐야

In [31]:
# 부산 시설 구분 확

busan_facility_type_summary = (
    port_facility_busan
    .groupby(["year", "prtAgNm", "useFeeKorNm"], as_index=False)
    .size()
    .rename(columns={"size": "count"})
)

display(busan_facility_type_summary)

    year prtAgNm useFeeKorNm  count
0   2021      부산           1      1
1   2021      부산          면제     15
2   2021      부산         전용료      1
3   2021      부산          접안      2
4   2021      부산         접안료    286
5   2021      부산          정박      4
6   2021      부산         정박료     83
7   2022      부산           1      1
8   2022      부산          면제     18
9   2022      부산         전용료      1
10  2022      부산          접안      2
11  2022      부산         접안료    279
12  2022      부산          정박      4
13  2022      부산         정박료     91
14  2024      부산           1      1
15  2024      부산          면제     64
16  2024      부산         전용료      1
17  2024      부산          접안      2
18  2024      부산         접안료    242
19  2024      부산          정박      4
20  2024      부산         정박료     89

In [32]:
# 부산 선석명 확인

busan_berth_summary = (
    port_facility_busan
    .dropna(subset=["berthNm"])
    .groupby(["year", "prtAgNm", "berthNm"], as_index=False)
    .size()
    .rename(columns={"size": "count"})
)

display(busan_berth_summary.head(50))

    year prtAgNm        berthNm  count
0   2021      부산            1부두      3
1   2021      부산           SK돌핀      1
2   2021      부산           감만부두      4
3   2021      부산      감만부두 동측안벽      1
4   2021      부산  감천 선기조합 조선소안벽      2
5   2021      부산        감천 제1부두      4
6   2021      부산        감천 제2부두      4
7   2021      부산        감천 제3부두      4
8   2021      부산        감천 제4부두      3
9   2021      부산        감천 제5부두      4
10  2021      부산        감천 제6부두      3
11  2021      부산        감천 제7부두      2
12  2021      부산        감천 중앙부두      6
13  2021      부산         강남조선안벽      1
14  2021      부산          관공선부두      1
15  2021      부산           다대부두      2
16  2021      부산         동국제강안벽      1
17  2021      부산           동명부두      4
18  2021      부산           동삼안벽      1
19  2021      부산         동일조선안벽      2
20  2021      부산           미원안벽      1
21  2021      부산  북컨테이너부두(신항부두)      6
22  2021      부산           삼경안벽      1
23  2021      부산           삼한안벽      4
24  2021      부산         서방파제안벽      3
25  2021      부산          신감만부두      3
26  2021      부산       신국제여객터미널     14
27  2021      부산      신선대 행정선부두      1
28  2021      부산          신선대부두      5
29  2021      부산           쌍용안벽      1
30  2021      부산           양곡부두      1
31  2021      부산         연안여객부두     11
32  2021      부산           연합부두      1
33  2021      부산           용호부두      1
34  2021      부산           우암부두      2
35  2021      부산         인천정유돌핀      1
36  2021      부산         자성대 부두      5
37  2021      부산           제1부두      2
38  2021      부산           제2부두      5
39  2021      부산           제3부두      7
40  2021      부산           제4부두      7
41  2021      부산           제7부두      4
42  2021      부산           제8부두      6
43  2021      부산           중앙부두      3
44  2021      부산      중앙부두 1물양장      1
45  2021      부산      중앙부두 2물양장      1
46  2021      부산           청학안벽      1
47  2021      부산           한전안벽      1
48  2022      부산            1부두      3
49  2022      부산           SK돌핀      1

In [33]:
# 선석 종류 개수만 보고 싶다면

busan_berth_count_summary = (
    port_facility_busan
    .dropna(subset=["berthNm"])
    .groupby(["year", "prtAgNm"], as_index=False)
    .agg(
        unique_berth_count=("berthNm", "nunique")
    )
)

display(busan_berth_count_summary)

   year prtAgNm  unique_berth_count
0  2021      부산                  48
1  2022      부산                  48
2  2024      부산                  49

In [34]:
# 부산 취급화물명 확인

busan_cargo_summary = (
    port_facility_busan
    .dropna(subset=["trtmntFrghtNm"])
    .groupby(["year", "prtAgNm", "trtmntFrghtNm"], as_index=False)
    .size()
    .rename(columns={"size": "count"})
)

display(busan_cargo_summary.head(50))

    year prtAgNm          trtmntFrghtNm  count
0   2021      부산                고철,, 철재      2
1   2021      부산              공영수산물도매시장      3
2   2021      부산                    관공선      2
3   2021      부산   군수품,,냉동어획물,,잡화,,컨테이너      6
4   2021      부산                 군용선,기타      1
5   2021      부산                  냉동어획물      4
6   2021      부산                     모래      1
7   2021      부산           목재,, 잡화,, 철재      5
8   2021      부산                   발전원료      1
9   2021      부산                   선박대기      3
10  2021      부산                     수리      5
11  2021      부산                   수리선박      1
12  2021      부산                 수리선박대기      5
13  2021      부산                시멘트,,잡화      1
14  2021      부산  시멘트,,철재,, 골재및 모래,, 잡화      2
15  2021      부산                액체,폐기화물      1
16  2021      부산                     양곡      1
17  2021      부산          어획물,, 철재,, 잡화      2
18  2021      부산                     없음      9
19  2021      부산                     여객      1
20  2021      부산             여객 컨테이너 잡화      1
21  2021      부산            여객, 컨테이너 잡화      1
22  2021      부산             여객,컨테이너 잡화      1
23  2021      부산                  연안여객선     11
24  2021      부산              위험물,냉동어획물      1
25  2021      부산                     유류      2
26  2021      부산            유류,, 모래,,잡화      4
27  2021      부산                 유류,케미칼      1
28  2021      부산       잡화,, 수리선박,, 선박대기      2
29  2021      부산               잡화,,수리대기      1
30  2021      부산                잡화,,어획물      3
31  2021      부산                 잡화,,유류      1
32  2021      부산                     철재      1
33  2021      부산            철재, 잡화, 어획물      2
34  2021      부산          철재,, 잡화,, 어획물      2
35  2021      부산                   컨테이너     26
36  2021      부산               컨테이너, 잡화     10
37  2021      부산              컨테이너,, 잡화     18
38  2021      부산              컨테이너,일반화물      5
39  2021      부산                 토사석적출장      1
40  2021      부산             폐기물,, 선박대기      2
41  2021      부산                    행정선      1
42  2022      부산                고철,, 철재      2
43  2022      부산              공영수산물도매시장      3
44  2022      부산                    관공선      2
45  2022      부산   군수품,,냉동어획물,,잡화,,컨테이너      6
46  2022      부산                 군용선,기타      1
47  2022      부산                  냉동어획물      4
48  2022      부산                     모래      1
49  2022      부산           목재,, 잡화,, 철재      5

마산 진해 vs 부산 비교표 만들기 - 부산을 비교 기준으로 잡으면, 창원 항만권역(마산 진해) 이 상대적으로 어느 정도 규모인지 설명하기 좋음

In [35]:
compare_ports = ["마산", "진해", "부산"]

port_facility_compare = port_facility[
    port_facility["prtAgNm"].astype(str).str.contains("|".join(compare_ports), na=False)
].copy()

port_facility_compare["lnlAblty"] = (
    port_facility_compare["lnlAblty"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("-", "0", regex=False)
    .str.strip()
)

port_facility_compare["lnlAblty"] = pd.to_numeric(
    port_facility_compare["lnlAblty"],
    errors="coerce"
).fillna(0)

facility_compare_summary = (
    port_facility_compare
    .groupby(["year", "prtAgNm"], as_index=False)
    .agg(
        facility_count=("fcltyKorNm", "count"),
        unique_facility_name=("fcltyKorNm", "nunique"),
        unique_berth_count=("berthNm", "nunique"),
        lnlAblty_sum=("lnlAblty", "sum"),
        lnlAblty_nonzero=("lnlAblty", lambda x: (x > 0).sum())
    )
)

display(facility_compare_summary)

,year,prtAgNm,facility_count,unique_facility_name,unique_berth_count,lnlAblty_sum,lnlAblty_nonzero
0,2021,마산,108,107,0,0.0,0
1,2021,부산,394,387,48,0.0,0
2,2021,진해,23,22,0,0.0,0
3,2022,마산,108,107,0,0.0,0
4,2022,부산,398,391,48,0.0,0
5,2022,진해,36,31,0,0.0,0
6,2024,마산,108,107,0,0.0,0
7,2024,부산,405,398,49,0.0,0
8,2024,진해,36,22,0,0.0,0

부산항은 마산항·진해항보다 항만시설 항목 수와 선석 정보가 훨씬 많이 확인된다. 반면 마산항과 진해항도 시설 기반은 존재하지만, 부산항에 비해 상대적으로 제한적인 규모로 나타남

- 부산항 시설 규모가 압도적으로 크다
- 마산항은 21, 22, 24년 시설 항목 수 일정하게 유지되어서 안정적인 항만시설 기반을 유지함
- 진해항은 21년도보다 22,24년도에 많아짐 (실제 시설 확충인지, 데이터 등록 방식 변화인지는 확인이 필요하니까 '증가한 것으로 확인된다' 정도로만 쓰기)
- unique_berth_count (선석 정보)는 부산만 확인됨 -> 마산 진해항에는 선석이 없다는 것이 아니라 마산항과 진해항 자료에서는 선석명 정보가 제공되지 않았고, 부산항 자료에서는 48~49개의 고유 선석명이 확인됨, 부산항은 선석명 정보도 구체적으로 제공되지만, 마산 진해는 선석명 데이터가 비어있는 것
- nlAblty_sum이 전부 0이고, lnlAblty_nonzero도 전부 0 -> 21, 22, 24년 마산 진해 부산 항만시설 자료에서 하역능력 수치가 유효하게 제공되지 않았음

=> 보고서 작성시 하역능력 수치가 0으로 제공되어 항만별 하역능력 총량 비교에는 한계가 있다. 따라서 본 분석에서는 시설 항목 수와 시설명, 선석명 제공 여부를 중심으로 항만시설 기반을 비교하였다.  이런식으로 작성


### 부산항은 마산항·진해항에 비해 시설 항목 수와 선석 정보가 훨씬 많이 확인되어 동남권 대표 항만으로서 큰 항만시설 기반을 가짐, 반면 마산항과 진해항도 항만시설 기반은 확인되지만, 부산항과 비교하면 상대적으로 제한적인 규모로 나타남. 따라서 창원 항만권역은 독립적인 대형 항만 물류 중심지라기보다는 부산항과 연계되는 배후 물류권역으로 해석 가능