In [1]:
import os 
os.chdir('/Users/mun-yeongmin/Downloads')

In [5]:
import pandas as pd
broker=pd.read_csv('경상남도 창원시_화물운송 주선업체 현황_20230516.csv', encoding='CP949')
broker.head()

   해당구  연번           업체명  대표자                              주소  비고
0  의창구   1      KGB창원합포점  이미숙  경상남도 창원시 의창구 금강로355번길 35 (소계동) NaN
1  의창구   2        국민포장이사  김세연  경상남도 창원시 의창구 남산로9번길 54-6 (팔용동) NaN
2  의창구   3       개미익스프레스  박중규  경상남도 창원시 의창구 남산로9번길 54-6 (팔용동) NaN
3  의창구   4  창원이사 경남익스프레스  안군상  경상남도 창원시 의창구 남산로9번길 54-6 (팔용동) NaN
4  의창구   5       삼성익스프레스  이보영  경상남도 창원시 의창구 남산로9번길 54-6 (팔용동) NaN

In [7]:
print(f"데이터 크기: {broker.shape}")
print(f"비고 NaN 개수: {broker['비고'].isna().sum()}")
print(f"비고 NaN 비율: {broker['비고'].isna().sum() / len(broker) * 100:.1f}%")
broker = broker.drop(columns=['비고'])
broker.head()

데이터 크기: (76, 6)
비고 NaN 개수: 76
비고 NaN 비율: 100.0%

   해당구  연번           업체명  대표자                              주소
0  의창구   1      KGB창원합포점  이미숙  경상남도 창원시 의창구 금강로355번길 35 (소계동)
1  의창구   2        국민포장이사  김세연  경상남도 창원시 의창구 남산로9번길 54-6 (팔용동)
2  의창구   3       개미익스프레스  박중규  경상남도 창원시 의창구 남산로9번길 54-6 (팔용동)
3  의창구   4  창원이사 경남익스프레스  안군상  경상남도 창원시 의창구 남산로9번길 54-6 (팔용동)
4  의창구   5       삼성익스프레스  이보영  경상남도 창원시 의창구 남산로9번길 54-6 (팔용동)

In [9]:
# 구별 업체 수
print(broker['해당구'].value_counts())

해당구
의창구      27
마산회원구    24
마산합포구     9
진해구       9
성산구       7
Name: count, dtype: int64

In [10]:
# 구별 집계
gu_broker = broker.groupby('해당구').size().reset_index()
gu_broker.columns = ['구', '주선업체수']
print(gu_broker.sort_values('주선업체수', ascending=False))

       구  주선업체수
3    의창구     27
1  마산회원구     24
0  마산합포구      9
4    진해구      9
2    성산구      7

In [11]:
# 진해구 vs 나머지
broker['진해여부'] = broker['해당구'].apply(lambda x: '진해구' if x == '진해구' else '기타')
print(broker.groupby('진해여부').size())

진해여부
기타     67
진해구     9
dtype: int64

In [ ]:
#운송업체 수 대비 주선업체 비율이 진해구가 제일 낮아요. 이게 공모전 핵심 논거로 쓸 수 있어요.
#"진해구는 운송업체 43개 대비 주선업체 9개로 비율 0.21 — 창원시 최하위. 화물-차량 연결 인프라가 가장 취약한 지역임에도 신항이 위치."